# Generated by Django 5.0 on 2023-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_member',
            field=models.BooleanField(default=False),
        ),
    ]
