# Generated by Django 5.0 on 2023-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='none', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
