# Generated by Django 5.0 on 2023-12-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0010_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
