# Generated by Django 5.0 on 2023-12-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0011_picks_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='outcome',
            field=models.BooleanField(default=False),
        ),
    ]
