# Generated by Django 5.0 on 2023-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0012_picks_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='picks',
            name='units',
            field=models.IntegerField(default=10, max_length=2),
            preserve_default=False,
        ),
    ]
