# Generated by Django 5.0 on 2023-12-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0013_picks_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='outcome',
            field=models.CharField(choices=[('WIN', 'WIN'), ('LOSS', 'LOSS'), ('NA', 'NA')], default='NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='picks',
            name='units',
            field=models.IntegerField(),
        ),
    ]
