# Generated by Django 5.0 on 2024-01-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0014_alter_picks_outcome_alter_picks_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picks',
            name='category',
            field=models.CharField(choices=[('NFL', 'NFL'), ('NBA', 'NBA'), ('NCAAF', 'NCAAF'), ('NCAAM', 'NCAAM'), ('NHL', 'NHL'), ('UFC', 'UFC')], default='NFL', max_length=5),
        ),
    ]
